# Generated by Django 4.1.1 on 2022-09-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokemodel',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
